language: node_js
node_js:
- stable
script:
- npm run coverage
after_succes:
- npm run report-coverage
branches:
 only:
 - development
notifications:
 email:
  recipients:
  - jeltecrabbe@gmail.com
  on_success: never        # default: change
  on_failure: always       # default: always